version: "3"

services:
  redis:
    image: "redis:4.0"
    ports:
      - "6380:6379"
    expose:
      - "6380"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: "redis-server /usr/local/etc/redis/redis.conf"  
